/** Runtime-only state. Persist only project data and referenced attachment blobs. */
export const state = {
  project: undefined,
  selected: null,
  view: "tree",
  showDocs: false,
  camera: {
    x: 0,
    y: 0,
    z: 1,
  },
  drag: null,
  history: [],
  future: [],
  blobs: new Map(),
  urls: new Map(),
  db: null,
  saveTimer: undefined,
  saveStatus: "",
  saveSerial: Promise.resolve(),
  fileContext: {},
  portraitPerson: null,
  toastTimer: undefined,
  modalResolve: null,
  docFilter: "",
  docTypeFilter: "",
  docStatusFilter: "",
  docFileFilter: "",
  docLayout: "list",
  docShowAll: false,
  groupFilter: "",
  exportingDiagram: false,
  comparisonPath: null,
  currentKinResult: null,
  initialized: false,
  renderIndex: null,
  searchLimit: 20,
  calendarMode: "month",
  calendarUndatedLimit: 80,
  calendarMonth: "",
  calendarDay: "",
  calendarSearch: "",
  calendarType: "",
  eventMode: "upcoming",
  eventSearch: "",
  eventType: "",
  eventDays: 90,
  eventOrder: "desc",
  eventLimit: 80,
  graphFocus: null,
  analysisHighlight: null,
  analysisReveal: new Set(),
  analysisExpandedGroups: new Set(),
  analysisReturnGroup: null,
  multiSelection: new Set(),
  selectionMode: false,
  touchMove: false,
  analysisResult: null,
  analysisMode: "path",
  analysisBusy: false,
  graphMeasureContext: null,
  graphWidthCache: new Map(),
  editorActive: false,
  savedDraft: null,
  startTemplate: "family",
  startBusy: false,
  pendingStartImport: false,
};
